apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-mariadb-persist-db-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 64Mi
# production piwigo galery with around 3k photos is using just 6MB