apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piwigo-persist-config-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
