{{- if and .Values.ingress.tls (index .Values.ingress.tls 0 "key_file") }}
apiVersion: v1
data:
  tls.crt: {{ .Files.Get "cert/cert.pem" | b64enc | quote }}
  tls.key: {{ .Files.Get "cert/key.pem" | b64enc | quote }}
kind: Secret
metadata:
  name: piwigo-ingress-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
{{- end }}
