apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "piwigo.fullname" . }}
  labels:
    {{- include "piwigo.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "piwigo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "piwigo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "piwigo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        # When mysql client connects to localhost, it automaticaly uses
        # UNIX Socket with path configured in config file. Different systems are
        # using different paths AND filenames. In production you can bypass this
        # by specifing IP '127.0.0.1' instead of 'localhost'. In this chart
        # I use it for initContainers example.
        #
        # Image bitnami/mariadb creates socket inside
        #       /opt/bitnami/mariadb/tmp/ named mysql.sock
        #
        # Debian expect it in directory
        #       /run/mysqld named mysqld.sock (note mysql.sock != mysqld.sock)
        # this init containers prepares link (to possibly non existent socket)
        # in shared volume 'mariadb-socket'
        - name: create-mysqld
          image: {{ .Values.mariadb.initImage }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - |
              cd /run/mysqld/
              ln -sf mysql.sock mysqld.sock
              ls -la
          volumeMounts:
          - name: mariadb-socket
            mountPath: /run/mysqld/
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          # UNIX Socket for interprocess communication
          - name: mariadb-socket
            mountPath: /run/mysqld/
          # Piwigo writes into following directories, they has
          # to be preserved:
          #   galleries upload plugins themes template-extension local _data
          - name: piwigo-presist-data
            mountPath: /var/www/html/galleries
            subPath: galleries
          - name: piwigo-presist-data
            mountPath: /var/www/html/upload
            subPath: upload
          - name: piwigo-presist-data
            mountPath: /var/www/html/plugins
            subPath: plugins
          - name: piwigo-presist-data
            mountPath: /var/www/html/themes
            subPath: themes
          - name: piwigo-presist-data
            mountPath: /var/www/html/template-extension
            subPath: template-extension
          - name: piwigo-presist-data
            mountPath: /var/www/html/local
            subPath: local
          - name: piwigo-presist-data
            mountPath: /var/www/html/_data
            subPath: _data
        - name: mariadb
          image: {{ .Values.mariadb.image }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              value: {{ .Values.mariadb.password }}
            - name: MARIADB_USER
              value: {{ .Values.mariadb.user }}
            - name: MARIADB_PASSWORD
              value: {{ .Values.mariadb.password }}
            - name: MARIADB_DATABASE
              value: {{ .Values.mariadb.database }}
          # custom bitnami/mariadb socket path `find / -type s``
          volumeMounts:
          - name: mariadb-socket
            mountPath: /opt/bitnami/mariadb/tmp/
            # path where to mount database directory is in docs of image https://hub.docker.com/r/bitnami/mariadb
          - name: mariadb-persist-db
            mountPath: /bitnami/mariadb
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - emptyDir: {}
          name: mariadb-socket
  volumeClaimTemplates:
  - metadata:
      name: mariadb-persist-db
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 64Mi
  - metadata:
      name: piwigo-presist-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
